export const ALL_CERTIFICATE_REQUEST = "ALL_CERTIFICATE_REQUEST";
export const ALL_CERTIFICATE_SUCCESS = "ALL_CERTIFICATE_SUCCESS";
export const ALL_CERTIFICATE_FAIL = "ALL_CERTIFICATE_FAIL";


export const NEW_CERTIFICATE_REQUEST = "NEW_CERTIFICATE_REQUEST";
export const NEW_CERTIFICATE_SUCCESS = "NEW_CERTIFICATE_SUCCESS";
export const NEW_CERTIFICATE_RESET = "NEW_CERTIFICATE_RESET";
export const NEW_CERTIFICATE_FAIL = "NEW_CERTIFICATE_FAIL";

export const UPDATE_CERTIFICATE_REQUEST = "UPDATE_CERTIFICATE_REQUEST";
export const UPDATE_CERTIFICATE_SUCCESS = "UPDATE_CERTIFICATE_SUCCESS";
export const UPDATE_CERTIFICATE_RESET = "UPDATE_CERTIFICATE_RESET";
export const UPDATE_CERTIFICATE_FAIL = "UPDATE_CERTIFICATE_FAIL";

export const REVOKE_CERTIFICATE_REQUEST = "REVOKE_CERTIFICATE_REQUEST";
export const REVOKE_CERTIFICATE_SUCCESS = "REVOKE_CERTIFICATE_SUCCESS";
export const REVOKE_CERTIFICATE_RESET = "REVOKE_CERTIFICATE_RESET";
export const REVOKE_CERTIFICATE_FAIL = "REVOKE_CERTIFICATE_FAIL";

export const CERTIFICATE_DETAILS_REQUEST = "CERTIFICATE_DETAILS_REQUEST";
export const CERTIFICATE_DETAILS_SUCCESS = "CERTIFICATE_DETAILS_SUCCESS";
export const CERTIFICATE_DETAILS_FAIL = "CERTIFICATE_DETAILS_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
